In [1]:
#data reading
#import pandas as pd


#libraries for encoding / vectorizing
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

#train test split
from sklearn.model_selection import train_test_split

#Ml model
from sklearn.naive_bayes import MultinomialNB

#checking accuracy
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
#importing dataset
df=pd.read_csv('ML_data.csv')

In [3]:
df.head()

,Unnamed: 0,index,category,description,keywords,plot
0,0,36956,politics,number of sanctuary congregations doubles sinc...,"(sanctuary, congregations, doubles, ’s electio...",sanctuary congregations doubles s election mo...
1,1,40229,politics,trump and russia: will anything be done? it is...,"(russia, apparent, russia's, election, stories...",russia apparent russia s election stories att...
2,2,85246,entertainment,kylie jenner dons a bra top & sheer skirt to '...,"(kylie jenner, skirt, paper towns', screening,...",kylie jenner skirt paper towns screening invi...
3,3,122674,art/culture,street photography in stockholm (pt. 2) i want...,"(street photography, quenches, authenticity, p...",street photography quenches authenticity pers...
4,4,180230,travel,the difference between inner and outer mongoli...,"(inner, outer mongolia, photos, flight, boston...",inner outer mongolia photos flight boston cap...

In [4]:
#deleting unwanted rows
df.drop(['Unnamed: 0','index','description','keywords'],axis=1, inplace=True)

In [5]:
df.head()

        category                                               plot
0       politics   sanctuary congregations doubles s election mo...
1       politics   russia apparent russia s election stories att...
2  entertainment   kylie jenner skirt paper towns screening invi...
3    art/culture   street photography quenches authenticity pers...
4         travel   inner outer mongolia photos flight boston cap...

### Encoding category column

In [6]:
le = LabelEncoder()
  
df['encoded_category']= le.fit_transform(df['category'])

In [7]:
df.head()

,category,plot,encoded_category
0,politics,sanctuary congregations doubles s election mo...,8
1,politics,russia apparent russia s election stories att...,8
2,entertainment,kylie jenner skirt paper towns screening invi...,3
3,art/culture,street photography quenches authenticity pers...,0
4,travel,inner outer mongolia photos flight boston cap...,10

In [8]:
#printing Encoded values corresponding to categories

a=df['category'].unique()
b=df['category']
c=df['encoded_category']
list1=[]
for i in a:
    for j in range(len(b)):
        if b[j]==i:
            list1.append(j)
            break


for i in list1:
    print(f"{b[i]} : {c[i]}")

politics : 8
entertainment : 3
art/culture : 0
travel : 10
environment : 4
sports : 9
international : 6
food & drink : 5
business : 1
lifestyle : 7
education/Tech/science : 2

### Vectorizing plot column

In [9]:
tfidf = TfidfVectorizer()
feature= tfidf.fit_transform(df['plot']).toarray()

### Creating X ,y variables

In [10]:
X=feature
y=df['encoded_category']

###  Train Test split

In [40]:

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)

### Fitting Naive_Bayes

In [41]:

clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

### Predict Values

In [42]:

y_pred=clf.predict(X_test)

### Calculating Model Accuracy

In [43]:
#calculating accuracy

accuracy_score(y_test,y_pred)

0.7112311015118791

In [44]:
#creating confusion metrics

confusion_matrix(y_test, y_pred)

array([[493,  16,  36,  60,  24,  14,  59,  47,  49,  10,  36],
       [ 13, 609,  56,  12,  29,  11,  28,  24,  35,  15,  20],
       [ 35,  90, 514,  22,  52,  10,  33,  29,  38,  21,  16],
       [ 50,  21,  25, 550,  23,  23,  14,  50,  65,  39,  17],
       [ 11,  24,  17,   6, 652,  18,  28,  24,  26,  10,  36],
       [  9,  15,   7,  11,  20, 685,   5,  23,   2,  13,  36],
       [ 26,  29,  17,   2,  41,   2, 608,   6,  39,   8,  13],
       [ 32,  48,  31,  21,  28,  40,  17, 553,  17,   9,  31],
       [ 19,  52,  15,  15,  27,   5,  76,   5, 573,  16,   6],
       [  4,  13,  18,  27,   9,   4,  24,  13,  25, 712,  13],
       [ 28,  19,  12,  10,  39,  37,  37,  19,   3,  19, 637]],
      dtype=int64)

In [45]:
#classification report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.68      0.58      0.63       844
           1       0.65      0.71      0.68       852
           2       0.69      0.60      0.64       860
           3       0.75      0.63      0.68       877
           4       0.69      0.77      0.73       852
           5       0.81      0.83      0.82       826
           6       0.65      0.77      0.71       791
           7       0.70      0.67      0.68       827
           8       0.66      0.71      0.68       809
           9       0.82      0.83      0.82       862
          10       0.74      0.74      0.74       860

    accuracy                           0.71      9260
   macro avg       0.71      0.71      0.71      9260
weighted avg       0.71      0.71      0.71      9260

In [17]:
a=X_test

In [30]:
b=list(y_test)

In [31]:
a[2]

array([0., 0., 0., ..., 0., 0., 0.])

In [32]:
b[2]

1

In [33]:
clf.predict([a[2]])

array([1])

In [34]:
clf.predict([a[1265]])

array([0])

In [35]:
b[1265]

9

In [38]:
clf.predict([a[81]])

array([3])

In [39]:
b[81]

3

In [23]:
print(b)

17037    7
16523    1
20480    1
12235    0
19024    7
        ..
14431    4
18463    1
7140     9
17518    9
18146    0
Name: encoded_category, Length: 9260, dtype: int32

In [26]:
list(y_test)

[7,
 1,
 1,
 0,
 7,
 5,
 4,
 8,
 4,
 0,
 8,
 7,
 7,
 10,
 7,
 8,
 2,
 10,
 3,
 4,
 2,
 3,
 6,
 4,
 8,
 10,
 0,
 10,
 1,
 2,
 0,
 8,
 9,
 1,
 3,
 7,
 5,
 2,
 10,
 9,
 1,
 2,
 8,
 3,
 7,
 7,
 1,
 9,
 0,
 5,
 4,
 7,
 2,
 7,
 7,
 5,
 0,
 2,
 6,
 5,
 8,
 7,
 1,
 9,
 10,
 8,
 9,
 1,
 0,
 7,
 9,
 8,
 5,
 0,
 6,
 1,
 7,
 5,
 0,
 8,
 0,
 3,
 7,
 2,
 3,
 9,
 10,
 3,
 3,
 8,
 6,
 3,
 3,
 2,
 10,
 2,
 1,
 10,
 3,
 0,
 8,
 0,
 7,
 3,
 5,
 10,
 10,
 6,
 7,
 2,
 9,
 0,
 9,
 3,
 0,
 4,
 5,
 6,
 7,
 5,
 5,
 3,
 0,
 1,
 0,
 1,
 10,
 7,
 0,
 1,
 5,
 8,
 7,
 10,
 2,
 9,
 3,
 6,
 7,
 7,
 3,
 1,
 7,
 8,
 2,
 4,
 10,
 5,
 8,
 7,
 5,
 4,
 5,
 6,
 6,
 4,
 5,
 0,
 6,
 2,
 1,
 1,
 1,
 2,
 2,
 3,
 10,
 5,
 8,
 0,
 0,
 6,
 5,
 4,
 7,
 8,
 7,
 1,
 7,
 1,
 7,
 10,
 7,
 5,
 0,
 1,
 9,
 6,
 4,
 6,
 5,
 10,
 4,
 4,
 0,
 4,
 1,
 6,
 4,
 2,
 8,
 2,
 0,
 1,
 2,
 8,
 2,
 2,
 1,
 6,
 3,
 2,
 1,
 4,
 4,
 7,
 4,
 3,
 7,
 5,
 5,
 0,
 5,
 4,
 10,
 0,
 0,
 3,
 7,
 2,
 4,
 2,
 4,
 1,
 1,
 3,
 10,
 2,
 8,
 0,
 1,
 0,
 7,
 4,
 5,
 3,
 9,
 8,
 8,
 6,
 7,
 3,
 10,
 6,
 9,
 5,
 3,
 0,
 0,
 6,
 1,
 6,
 9,
 7,
 1,
 8,
 5,
 1,
 9,
 1,
 1,
 7,
 7,
 3,
 2,
 9,
 1,
 5,
 8,
 7,
 4,
 5,
 7,
 8,
 9,
 5,
 4,
 8,
 1,
 4,
 10,
 2,
 10,
 10,
 5,
 6,
 2,
 2,
 6,
 9,
 6,
 4,
 4,
 7,
 4,
 3,
 0,
 8,
 3,
 9,
 0,
 7,
 4,
 6,
 5,
 9,
 9,
 6,
 0,
 0,
 4,
 3,
 7,
 2,
 2,
 7,
 0,
 9,
 5,
 9,
 3,
 9,
 7,
 1,
 2,
 1,
 0,
 1,
 8,
 8,
 10,
 8,
 10,
 6,
 8,
 6,
 3,
 4,
 9,
 7,
 3,
 4,
 10,
 1,
 0,
 0,
 0,
 9,
 4,
 1,
 6,
 9,
 8,
 5,
 1,
 4,
 1,
 4,
 1,
 7,
 7,
 3,
 8,
 6,
 4,
 3,
 6,
 8,
 4,
 6,
 9,
 4,
 5,
 8,
 4,
 10,
 0,
 7,
 5,
 10,
 7,
 5,
 9,
 8,
 4,
 3,
 4,
 2,
 1,
 0,
 10,
 6,
 5,
 7,
 4,
 5,
 0,
 7,
 6,
 1,
 3,
 8,
 7,
 8,
 9,
 8,
 6,
 5,
 3,
 10,
 0,
 2,
 1,
 3,
 0,
 0,
 3,
 4,
 5,
 10,
 9,
 10,
 4,
 8,
 1,
 10,
 3,
 9,
 8,
 9,
 8,
 8,
 3,
 2,
 2,
 6,
 6,
 8,
 4,
 5,
 6,
 2,
 10,
 10,
 3,
 10,
 6,
 5,
 3,
 7,
 3,
 2,
 2,
 5,
 9,
 0,
 3,
 6,
 5,
 4,
 0,
 3,
 0,
 7,
 1,
 0,
 7,
 10,
 9,
 6,
 4,
 2,
 4,
 3,
 5,
 5,
 8,
 0,
 0,
 6,
 6,
 10,
 7,
 4,
 4,
 6,
 10,
 0,
 2,
 1,
 10,
 5,
 2,
 3,
 6,
 6,
 4,
 6,
 0,
 10,
 4,
 2,
 3,
 9,
 0,
 2,
 8,
 4,
 6,
 3,
 8,
 8,
 10,
 5,
 3,
 2,
 9,
 1,
 4,
 7,
 5,
 4,
 3,
 6,
 3,
 0,
 9,
 10,
 7,
 2,
 6,
 3,
 7,
 7,
 3,
 8,
 0,
 9,
 5,
 10,
 6,
 6,
 6,
 2,
 2,
 7,
 1,
 4,
 4,
 5,
 10,
 5,
 1,
 8,
 8,
 5,
 10,
 8,
 10,
 4,
 1,
 8,
 2,
 3,
 2,
 6,
 10,
 6,
 4,
 1,
 1,
 3,
 9,
 0,
 2,
 8,
 1,
 4,
 6,
 3,
 1,
 9,
 8,
 9,
 10,
 10,
 5,
 0,
 9,
 6,
 0,
 1,
 1,
 4,
 5,
 8,
 3,
 0,
 8,
 0,
 5,
 7,
 1,
 3,
 6,
 9,
 9,
 8,
 8,
 6,
 0,
 5,
 3,
 8,
 7,
 7,
 7,
 4,
 2,
 4,
 0,
 1,
 3,
 6,
 3,
 9,
 4,
 8,
 5,
 6,
 0,
 2,
 8,
 0,
 9,
 8,
 7,
 9,
 5,
 10,
 10,
 1,
 0,
 9,
 9,
 10,
 3,
 7,
 10,
 6,
 3,
 10,
 6,
 4,
 4,
 10,
 10,
 7,
 5,
 9,
 10,
 2,
 8,
 5,
 3,
 10,
 3,
 4,
 1,
 5,
 0,
 3,
 9,
 6,
 9,
 4,
 8,
 4,
 2,
 9,
 8,
 6,
 8,
 3,
 7,
 6,
 4,
 7,
 2,
 0,
 1,
 9,
 6,
 7,
 1,
 1,
 9,
 3,
 6,
 7,
 2,
 4,
 9,
 2,
 10,
 7,
 1,
 8,
 8,
 6,
 7,
 1,
 10,
 7,
 6,
 0,
 4,
 2,
 2,
 9,
 5,
 1,
 7,
 0,
 10,
 8,
 8,
 1,
 1,
 1,
 8,
 0,
 4,
 8,
 0,
 10,
 5,
 3,
 6,
 2,
 8,
 8,
 0,
 5,
 7,
 7,
 4,
 0,
 2,
 4,
 4,
 1,
 0,
 6,
 9,
 0,
 10,
 8,
 1,
 6,
 7,
 4,
 0,
 1,
 4,
 10,
 7,
 4,
 1,
 9,
 3,
 9,
 6,
 10,
 2,
 4,
 9,
 0,
 3,
 0,
 3,
 3,
 10,
 10,
 6,
 0,
 8,
 10,
 0,
 10,
 8,
 2,
 8,
 9,
 3,
 7,
 3,
 2,
 7,
 4,
 6,
 0,
 4,
 9,
 6,
 7,
 0,
 8,
 0,
 10,
 9,
 8,
 9,
 0,
 6,
 8,
 3,
 7,
 5,
 2,
 5,
 0,
 9,
 7,
 5,
 1,
 10,
 4,
 4,
 0,
 0,
 5,
 7,
 7,
 10,
 4,
 8,
 4,
 9,
 7,
 9,
 0,
 0,
 8,
 2,
 1,
 9,
 8,
 9,
 1,
 7,
 5,
 3,
 0,
 6,
 1,
 10,
 10,
 0,
 6,
 4,
 4,
 3,
 2,
 1,
 8,
 4,
 4,
 9,
 8,
 9,
 3,
 0,
 3,
 6,
 8,
 10,
 2,
 0,
 1,
 7,
 2,
 4,
 4,
 2,
 1,
 9,
 9,
 6,
 9,
 1,
 9,
 6,
 6,
 7,
 1,
 7,
 1,
 5,
 0,
 2,
 3,
 5,
 5,
 8,
 0,
 9,
 8,
 0,
 4,
 5,
 6,
 2,
 0,
 4,
 2,
 0,
 5,
 5,
 8,
 7,
 5,
 0,
 0,
 5,
 8,
 2,
 7,
 7,
 9,
 9,
 4,
 3,
 4,
 8,
 10,
 6,
 6,
 3,
 3,
 5,
 1,
 4,
 3,
 7,
 1,
 2,
 10,
 10,
 0,
 2,
 7,
 0,
 3,
 3,
 8,
 9,
 8,
 1,
 10,
 10,
 4,
 3,
 7,
 0,
 4,
 7,
 4,
 2,
 7,
 10,
 7,
 1,
 8,
 2,
 10,
 9,
 4,
 8,
 9,
 7,
 6,
 0,
 2,
 6,
 0,
 5,
 10,
 5,
 7,
 ...]